### PR TITLE
Improve infrastructure (CI, Linting, Docs Build)

### PR DESCRIPTION
**Pull request by hmgaudecker**
If there is need for speed.

### CODE REVIEW

**Comment by hmgaudecker** [comment]
Broadening the scope a bit...

**Comment by hmgaudecker** [comment]
Some economies of scope with the review of [GETTSIM #470](https://github.com/iza-institute-of-labor-economics/gettsim/pull/470) here -- exactly the same :smile:

**Comment by janosg** [comment]
Runtime of github actions is roughly cut in half due to mamba and caching environments. I also got rid of tox entirely. @hmgaudecker maybe you want to copy this for gettsim.

**Comment by hmgaudecker** [comment]
Thanks @janosg ! Will copy, but for doing so common formatting of yaml files is really helpful.  I added yamlfix and yamllint hooks, but was unable to push because @timmens was always faster than me and things interacted with his changes. 

Tim, could you try to merge the yamlfix branch into this?

**Comment by janosg** [comment]
Turns out that the notebooks were not actually executed on readthedocs and shown without outputs, due to this line in conf.py:

```python
nbsphinx_execute = "never"
```

Unfortunately, they also run way too long to be executed remotely. So I keep the mamba changes but otherwise revert to building notebooks locally and committing them with outputs.

**Comment by hmgaudecker** [comment]
Do all notebooks run for too long? Else use `"auto"` and commit only outputs of those with long runtimes?

**Review by janosg — APPROVED** [review]

**Review by timmens — APPROVED** [review]

**Pull request merged**
