### PR TITLE
Move from Azure to Github Actions.

### PR DESCRIPTION
**Pull request by tobiasraabe**
The switch from azure pipelines to github actions is motivated by:

- Faster runtimes (mainly in the creation of test environments)
- Hopefully less problems with environment creation on windows

### CODE REVIEW

**Comment by tostenzel** [comment]
# [Codecov](https://codecov.io/gh/OpenSourceEconomics/estimagic/pull/125?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@ec43ebf`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/OpenSourceEconomics/estimagic/pull/125?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##             master     #125   +/-   ##
=========================================
  Coverage          ?   78.50%           
=========================================
  Files             ?       32           
  Lines             ?     1963           
  Branches          ?        0           
=========================================
  Hits              ?     1541           
  Misses            ?      422           
  Partials          ?        0           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/OpenSourceEconomics/estimagic/pull/125?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/OpenSourceEconomics/estimagic/pull/125?src=pr&el=footer). Last update [ec43ebf...5ed1f12](https://codecov.io/gh/OpenSourceEconomics/estimagic/pull/125?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by tobiasraabe** [comment]
@tostenzel I think Github has mistakenly used your handle to push the coverage report 😄.

**Comment by janosg** [comment]
Or maybe @tostenzel hast a side job as bot on GitHub.

**Comment by tostenzel** [comment]
This is a wild behavior :D I hope git is not starting to manipulate repos under my name :D

**Pull request merged**
