### PR TITLE
Updated optimize.py to ignore performance warnings

### PR DESCRIPTION
**Pull request by vgangaprasad**
Added the following import and logic to ignore the pandas performance warnings

from warnings import simplefilter
simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

### CODE REVIEW

**Comment by janosg** [comment]
Hi Vijay,

that looks good now, but you still have to remove the `pr: none` line from [this file](https://github.com/OpenSourceEconomics/estimagic/blob/master/.azure-pipelines.yml) for our tests to run. You don't need to make a new PR for that. You can just make the change on your fork and push again. 

Best,
Janos

**Comment by vgangaprasad** [comment]
Janos, removed PR:None

**Comment by janosg** [comment]
Thanks, now the tests are triggered. The failing checks are because you did not run the black formatter over the file you changed. You can do that by activating the estimagic environment and ``tox`` or by running the pre-commit hooks manually. The procedure is also described [here](https://estimagic.readthedocs.io/en/master/contributing/how-to.html)

**Comment by janosg** [comment]
Alternatively, you could give me push access in your fork so I can make the change myself.

**Comment by vgangaprasad** [comment]
> Alternatively, you could give me push access in your fork so I can make the change myself. I tried the steps in the contributing guide and when i executed tox, it was throwing errors, i am attaching it for your reference.
[tox errors.txt](https://github.com/OpenSourceEconomics/estimagic/files/3695297/tox.errors.txt)


Hi Janos,

I have added you as a collaborator to my repo, please make the changes.

**Comment by vgangaprasad** [comment]
> 
> 
> Thanks a lot for your contribution and sorry for the trouble ;-)

Hi Janos,
Np, in fact i thought i was the trouble maker.. I can help in any way i could, if you want me to learn about the whole process and setup the environment and come back again for helping then i could do that. 

If you can give me pointers on what to focus on or learn then that would help me in educating myself and come back and contribute more.

Thanks,
Vijay

**Comment by janosg** [comment]
I sent you an email because. I hope the email address on your profile is still correct?

**Pull request merged**
